worker_processes 1;
error_log /dev/stderr warn;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

stream {
    resolver 127.0.0.11 valid=10s ipv6=off;

    upstream acervo_s3 {
        zone acervo_s3 64k;
        server acervo-seaweedfs-interno:8333 resolve;
    }

    upstream acervo_metricas {
        zone acervo_metricas 64k;
        server acervo-seaweedfs-interno:9091 resolve;
    }

    server {
        listen 8333;
        proxy_pass acervo_s3;
    }

    server {
        listen 9091;
        proxy_pass acervo_metricas;
    }
}
